apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: inventoryapi
  name: inventoryapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: inventoryapi
  type: LoadBalancer
status:
  loadBalancer: {}
